// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"time"
)

type Ticket struct {
	ID          int64     `db:"id" json:"id"`
	Title       string    `db:"title" json:"title"`
	Description string    `db:"description" json:"description"`
	AssignedTo  int64     `db:"assigned_to" json:"assigned_to"`
	CreatedBy   int64     `db:"created_by" json:"created_by"`
	DueDate     time.Time `db:"due_date" json:"due_date"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
}

type User struct {
	ID        int64     `db:"id" json:"id"`
	Username  string    `db:"username" json:"username"`
	Email     string    `db:"email" json:"email"`
	Password  string    `db:"password" json:"password"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}
