// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"context"
)

type Querier interface {
	CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTicket(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetTicketByID(ctx context.Context, id int64) (Ticket, error)
	GetTicketForUpdate(ctx context.Context, id int64) (Ticket, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserForUpdate(ctx context.Context, email string) (User, error)
	ListTickets(ctx context.Context, arg ListTicketsParams) ([]Ticket, error)
	ListTicketsByUser(ctx context.Context, arg ListTicketsByUserParams) ([]Ticket, error)
	ListTicketsForUser(ctx context.Context, arg ListTicketsForUserParams) ([]Ticket, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
